### ISSUE TITLE
What is hctsa?

### ISSUE THREAD

**Issue by maartenmennes** [Brainhack-Proceedings-2015/Fulcher_HBM_Comparable_NITIME#1]
Hi Ben,

good write-up of your project! Would you be able to provide a bit more insight into the bacground of hctsa for those readers unfamiliar with it (such as myself)? I also suggest including the link to the matlab package/website for reference. It's especially the timeseries to feature-vectors that's unclear to me.

**Comment by benfulcher** [comment]
Hi, thanks for the feedback. Alright I've had a go at this. Let me know if it's any clearer now, or if you think something additional still needs explaining

**Comment by maartenmennes** [comment]
Good additions, thanks!
