### ISSUE TITLE
How extensible are these libraries beyond Nitime?

### ISSUE THREAD

**Issue by maartenmennes** [Brainhack-Proceedings-2015/Fulcher_HBM_Comparable_NITIME#2]
Could you provide a bit more information about the specific format of Nitime data? How easy would it be to apply your new libraries to data that are not in that format (e.g., just numpy arrays).

**Comment by benfulcher** [comment]
Ok, yep, I've added a comment on this :)

**Comment by maartenmennes** [comment]
all clear now, thanks!
