### ISSUE TITLE
Future Goals?

### ISSUE THREAD

**Issue by maartenmennes** [Brainhack-Proceedings-2015/Fulcher_HBM_Comparable_NITIME#3]
What are the future goals of this project? Do you want to bring in the complete hctsa library? Or ar the current basic functions enough for intial neuroimaging timeseries analysis? How extensible is this to e.g., EEG or MEG data?

**Comment by benfulcher** [comment]
I've added a comment on this. All issues should have been addressed in https://github.com/Brainhack-Proceedings-2015/Fulcher_HBM_Comparable_NITIME/commit/67e95726f28fa0954d8dbb85c502e5a2f3e0696b

**Comment by maartenmennes** [comment]
all good, thanks!
