### ISSUE TITLE
partials

### ISSUE THREAD

**Issue by ccraddock** [Brainhack-Proceedings-2015/Fulcher_HBM_Comparable_NITIME#4]
Hey Ben,

Its looking good. Just one more thing. Where you mention "partials" in the result section, would you please clarify whether you are referring to partial functions and briefly describe the benefit? As it is, it is hard for non-pythonistas to understand what you mean here.

Thanks,
Cameron

**Comment by benfulcher** [comment]
Thanks -- yep, I've added a brief explanation. Let me know if this is clearer now.
